# -*- coding: utf-8 -*-
"""ESTOQUE2.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQRgkCD_TrYTmEFDpkEh4X9VXgsseMh5
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile estoque.py
# def cadastrar_produto(nome, quantidade, preco, categoria, estoque):
#     if nome in estoque:
#         estoque[nome][0] += quantidade
#         estoque[nome][1] = preco
#         print(f"Produto '{nome}' atualizado! Nova quantidade: {int(estoque[nome][0])}. Novo preço: R${estoque[nome][1]:.2f}")
#     else:
#         estoque[nome] = [quantidade, preco, categoria]
#         print(f"Produto '{nome}' adicionado. Quantidade: {int(quantidade)}, Preço: R${preco:.2f}")
# 
# def consultar_estoque(estoque):
#     if not estoque:
#         print("Estoque vazio.")
#     else:
#         print(f"{'PRODUTO':<15} {'CATEGORIA':<15} {'QUANTIDADE':>8} {'PREÇO':>12}")
#         for nome, dados in estoque.items():
#             quantidade, preco, categoria = dados[0], dados[1], dados[2]
#             print(f"{nome:<15} | {categoria:<15} | {int(quantidade):>4} | R${preco:>8.2f}")
# 
# 
# def estoque_baixo(estoque, limite):
#     poucos_produtos = []
#     for nome, dados in estoque.items():
#         quantidade = dados[0]
#         if quantidade <= limite:
#             poucos_produtos.append((nome, quantidade))
#     if not poucos_produtos:
#         print("Nenhum produto com estoque baixo.")
#     else:
#         print(f"Produtos com estoque baixo (limite: {int(limite)} unidades):")
#         for nome, quantidade in poucos_produtos:
#             print(f"Produto: {nome} Quantidade: {int(quantidade)}")
# 
# 
# def preco_total(estoque):
#     total = 0
#     for dados in estoque.values():
#         total += dados[0] * dados[1]
#     return total
# 
# def registrar_entrada(nome, quantidade, estoque):
#   nome = nome.strip()
#   if not nome:
#     print("Erro: o nome do produto não pode estar vazio!")
#     return False
#   if quantidade <= 0:
#     print("Erro: a quantidade deve ser maior que zero!")
#     return False
#   if nome in estoque:
#       estoque[nome][0] += quantidade
#       print(f"Entrada registrada com sucesso!")
#       print(f"Novo estoque de '{nome}': {int(estoque[nome][0])} unidades.")
#       return True
#   else:
#     print("Produto não encontrado no estoque.")
#     return False
# 
# 
# def registrar_saida(nome, quantidade, estoque):
#     nome = nome.strip()
#     if not nome:
#         print("Erro: o nome do produto não pode estar vazio!")
#         return False
#     if quantidade <= 0:
#         print("Erro: a quantidade deve ser maior que zero!")
#         return False
#     if nome in estoque:
#         if estoque[nome][0] >= quantidade:
#             estoque[nome][0] -= quantidade
#             print(f"Saída registrada com sucesso! Novo estoque de '{nome}': {int(estoque[nome][0])} unidades.")
#             return True
#         else:
#             print("Quantidade insuficiente no estoque.")
#             return False
#     else:
#         print("Produto não encontrado.")
#         return False

from estoque import cadastrar_produto, consultar_estoque, estoque_baixo, preco_total, registrar_entrada, registrar_saida
estoque = {}

while True:
    print("\n-----Menu-----")
    print("Digite 1 para cadastrar ou atualizar produtos")
    print("Digite 2 para consultar o estoque")
    print("Digite 3 para saber o preço total")
    print("Digite 4 para ver produtos com estoque baixo")
    print("Digite 5 para registrar entrada de produto")
    print("Digite 6 para registrar saída de produto")
    print("Digite 7 para sair do estoque")

    o = input("\nEscolha uma opção: ")

    if o == "1":
        nome = input("Digite o nome do produto: ")
        quantidade = float(input("\nDigite a quantidade: "))
        preco = float(input("\nDigite o valor do produto: R$ "))
        categoria = input("\nDigite a categoria do produto: ")
        cadastrar_produto(nome, quantidade, preco, categoria, estoque)

    elif o == "2":
        consultar_estoque(estoque)

    elif o == "3":
        print(f"\nPreço total do estoque: R${preco_total(estoque):.2f}")

    elif o == "4":
        limite = float(input("Digite o limite mínimo de quantidade: "))
        estoque_baixo(estoque, limite)

    elif o == "5":
        nome = input("Digite o nome do produto: ")
        quantidade = float(input("Digite a quantidade que entrou: "))
        registrar_entrada(nome, quantidade, estoque)

    elif o == "6":
        nome = input("Digite o nome do produto: ")
        quantidade = float(input("Digite a quantidade que saiu: "))
        registrar_saida(nome, quantidade, estoque)

    elif o == "7":
        print("Saindo do estoque...")
        break

    else:
        print("Opção inválida.")